name: RLD Creative
favicon: null
layout_spectrum: 0.24952
typography_spectrum: 0.4547043170314282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7310850508511066
  lightness: 0.13519625808112323
  saturation: 0.583178928354755
  rhythmicContrast: 0.40651983371935785
purpose: []
